force-app/main/default/objects/Zoom_Meeting__c/Zoom_Meeting__c.object-meta.xml
<CustomObject>
    <label>Zoom Meeting</label>
    <nameField>
        <label>Zoom Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Meeting__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asia/Kathmandu</fullName>
                <default>true</default>
                <label>Asia/Kathmandu</label>
            </value>
            <value>
                <fullName>Asia/Delhi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Zoom_Meeting_Id__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Meeting_Id__c</fullName>
    <label>Zoom Meeting Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZoomIntegration.cls
public class ZoomIntegration {
    public static void createMeeting(Zoom_Meeting__c meeting){
        WrapperMeeting payload = new WrapperMeeting();
        payload.topic = meeting.Topic__c;
        payload.type = 2;
        payload.start_time = meeting.Start_Time__c.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        payload.duration = Integer.valueOf(meeting.Duration__c);
        payload.timezone = meeting.Time_Zone__c;
        
        String jsonBody = JSON.serialize(payload);
        HttpRequest req = new HttpRequest();
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setEndpoint('callout:Zoom_Integration/v2/users/me/meetings');
        req.setBody(jsonBody);
        sendRequest(req, meeting.Id, 'CREATE');
    }

    public static void cancelMeeting(Zoom_Meeting__c meeting){
        if(String.isBlank(meeting.Zoom_Meeting_Id__c)){
            return;
        }
        HttpRequest req = new HttpRequest();
        req.setMethod('DELETE');
        req.setEndpoint('callout:Zoom_Integration/v2/meetings/' +meeting.Zoom_Meeting_Id__c);
        sendRequest(req, meeting.Id, 'CANCEL');
    }
	
    public static void updateMeeting(Zoom_Meeting__c meeting){
        WrapperMeeting payload = new WrapperMeeting();
        payload.topic = meeting.Topic__c;
        payload.start_time = meeting.Start_Time__c.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        payload.duration = Integer.valueOf(meeting.Duration__c);
        payload.timezone = meeting.Time_Zone__c;
    
        String jsonBody = JSON.serialize(payload);
        HttpRequest req = new HttpRequest();
        req.setMethod('PATCH');
        req.setHeader('Content-Type', 'application/json');
        req.setEndpoint('callout:Zoom_Integration/v2/meetings/' + meeting.Zoom_Meeting_Id__c);
        req.setBody(jsonBody);
        sendRequest(req, meeting.Id, 'UPDATE');
    }
    private static void sendRequest(HttpRequest req, Id recordId, String operationType){
        Http http = new Http();
        HttpResponse res = http.send(req);
        Integer statusCode = res.getStatusCode();
        if(statusCode == 201 && operationType == 'CREATE'){
            Map<String,Object> responseMap =(Map<String,Object>) JSON.deserializeUntyped(res.getBody());
            update new Zoom_Meeting__c(
                Id = recordId,
                Zoom_Meeting_Id__c = String.valueOf(responseMap.get('id')),
                Join_URL__c = String.valueOf(responseMap.get('join_url')),
                Status__c = 'Scheduled'
            );
        }
        else if(statusCode == 204 && operationType == 'CANCEL'){
            update new Zoom_Meeting__c(Id = recordId,Status__c = 'Cancelled');
        }
        else if(statusCode == 204 && operationType == 'UPDATE'){
            update new Zoom_Meeting__c(Id = recordId,Status__c = 'Scheduled');
        }
        else{
            update new Zoom_Meeting__c(Id = recordId,Status__c = 'Failed');
        }
	}

    public class WrapperMeeting {
        public String topic;
        public Integer type;
        public String start_time;
        public Integer duration;
        public String timezone;
    }
}